language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
script:
    - npm run test

before_deploy:
    - npm run build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
        branch: main
